export const UPDATE_STATISTICS = "UPDATE_STATISTICS";
export const UPDATE_FOOD_CAMPS = "UPDATE_FOOD_CAMPS";
export const UPDATE_HOSPITALS = "UPDATE_HOSPITALS";
export const SAVE_STATISTIC = "SAVE_STATISTIC";
export const SAVE_FOOD_CAMP = "SAVE_FOOD_CAMP";
export const SAVE_HOSPITAL = "SAVE_HOSPITAL";

export const UPDATE_PROFILE = "UPDATE_PROFILE";